datagrid:
  elasticsearch:
    cluster-nodes: ${CLUSTER_NODES}
    xpack: ${HTTPS:false}
    socketTimeout: ${ES_SOCKET_TIMEOUT:90000}
    connectionTimeout: ${ES_CONNECTION_TIMEOUT:10000}
    indexes: ${INDEX_NAMES}